/** The Dot computer start page: real profile, actual time, and only apps installed on its Linux desktop. */
export function desktopHome(_sessionId:string):string{return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your dot’s computer</title><style>
:root{font-family:Arial,sans-serif;color:#4d4941;background:#faf8ef;--paper:#faf8ef;--accent:#ffe156}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--paper);overflow:auto}.patterns{position:fixed;inset:0;pointer-events:none;opacity:.16;overflow:hidden}.patterns span{position:absolute;color:var(--accent);filter:brightness(.58);font-size:38px;font-weight:400;transform:rotate(var(--angle,0deg))}main{position:relative;max-width:650px;margin:0 auto;padding:30px 36px 34px;text-align:center}.profile{display:flex;flex-direction:column;align-items:center;gap:8px}.avatar{width:100px;height:100px;object-fit:contain;filter:drop-shadow(0 8px 8px #00000008)}.clock{display:flex;justify-content:center;align-items:baseline;gap:8px;line-height:1;letter-spacing:-3px}.clock strong{font-size:62px;font-weight:650}.clock small{font-size:10px;letter-spacing:0;font-weight:400}.welcome{font-size:22px;letter-spacing:-.4px;margin:7px 0 26px;font-weight:400}.tip{max-width:300px;margin:0 auto 12px;padding:12px 18px;border-radius:12px;background:#ffffffb5;line-height:1.35;font-size:12px;color:#5b5850}.apps{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:28px 16px}.app{display:flex;flex-direction:column;align-items:center;gap:9px;border:0;border-radius:12px;padding:8px 3px;background:transparent;color:inherit;cursor:pointer;font:inherit}.app:hover{background:#ffffff70}.app:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.app img,.app .fallback{width:46px;height:46px;object-fit:contain}.app .fallback{display:grid;place-items:center;background:#fff9;border-radius:12px;font-size:24px}.app span{font-size:12px}.notice{font-size:12px;min-height:18px;margin-top:20px;line-height:1.4}footer{font-size:10px;color:#898579;margin-top:18px}@media(max-width:600px){main{padding:24px 15px}.apps{gap:22px 5px}.clock strong{font-size:56px}.welcome{font-size:20px}}@media(prefers-reduced-motion:no-preference){.app{transition:background .15s}}
</style></head><body><div class="patterns" aria-hidden="true"></div><main id="dot-home"><div class="tip">Bilgisayarımda yaptığım işleri burada izleyebilir veya kontrolü devralabilirsin.</div><div class="profile"><img class="avatar" alt="" hidden><div class="clock"><strong id="time"></strong><small id="period"></small></div><h1 class="welcome" id="welcome"></h1></div><div class="apps" aria-label="Uygulamalar"></div><div class="notice" role="status"></div><footer>Tarayıcı · Terminal · Dosyalar</footer></main><script>
let profile;const main=document.querySelector('main'),apps=document.querySelector('.apps'),notice=document.querySelector('.notice');
function clock(){const d=new Date();document.getElementById('time').textContent=d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}).replace(/\\s?[AP]M/,'');document.getElementById('period').textContent=d.getHours()<12?'AM':'PM'}clock();setInterval(clock,1000);
const symbols=['♧','♤','◇','♧','◌','♧','◇','♤','◌','♧','♤','◇'];const positions=[[8,10],[23,20],[69,13],[86,34],[13,45],[78,63],[36,73],[63,83],[8,87],[89,84],[73,37],[29,46]];symbols.forEach((s,i)=>{const e=document.createElement('span');e.textContent=s;e.style.left=positions[i][0]+'%';e.style.top=positions[i][1]+'%';e.style.setProperty('--angle',(i*37%70-35)+'deg');document.querySelector('.patterns').append(e)});
async function update(){try{const r=await fetch('profile');if(!r.ok)return;const next=await r.json();profile=next;document.documentElement.style.setProperty('--paper',next.colors.light);document.documentElement.style.setProperty('--accent',next.colors.base);document.getElementById('welcome').textContent='Merhaba, '+next.appearance.name;const image=document.querySelector('.avatar');if(next.appearance.avatarImage){image.src=next.appearance.avatarImage;image.hidden=false}else{image.hidden=true;image.removeAttribute('src')}const ids=next.apps.map(a=>a.id).join('|');if(apps.dataset.ids===ids)return;apps.dataset.ids=ids;apps.replaceChildren();for(const app of next.apps){const b=document.createElement('button');b.type='button';b.className='app';const icon=document.createElement('img');icon.alt='';icon.src='icon/'+app.id;icon.onerror=()=>{const f=document.createElement('span');f.className='fallback';f.textContent=app.name[0];icon.replaceWith(f)};const label=document.createElement('span');label.textContent=app.name;b.append(icon,label);b.onclick=async()=>{notice.textContent='';try{const r=await fetch('launch/'+app.id+'?k='+profile.csrf,{method:'POST'});if(r.status===409){notice.textContent='Önce Codex’te “Kontrolü devral”ı seç.';return}if(!r.ok)throw Error();notice.textContent=app.name+' açılıyor…';setTimeout(()=>notice.textContent='',2200)}catch{notice.textContent='Uygulama açılamadı. Tekrar dene.'}};apps.append(b)}}catch{}}
update();setInterval(update,1500);
</script></body></html>`;}
