import {EventEmitter} from 'node:events';import {spawn,execFile,type ChildProcess} from 'node:child_process';import {promisify} from 'node:util';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import type {ComputerDesktop} from './desktop-contract.js';import type {StreamInput} from './stream-input.js';import type {DesktopAppearance} from './desktop.js';
const run=promisify(execFile),valid=(id:string)=>{if(!/^[a-f0-9-]{36}$/i.test(id))throw Error('Invalid desktop session');};
/** Connected user's actual primary Windows display. Never controls the lock/logon screen. */
export class WindowsDesktop extends EventEmitter implements ComputerDesktop{
 private controls=new Map<string,'user'|'agent'>();private activeUser?:string;private child?:ChildProcess;private exe='';private latest?:Buffer;private failure='';private starting?:Promise<void>;private idle?:ReturnType<typeof setTimeout>;
 private seq=0;private pending=new Map<number,{resolve:()=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 constructor(private dataDir:string,private workspace:string){super();if(process.platform!=='win32')throw Error('PC desktop currently requires Windows.');}
 async start(){await mkdir(this.dataDir,{recursive:true});const source=fileURLToPath(new URL('./windows-desktop.cs',import.meta.url)),bytes=await readFile(source),hash=createHash('sha256').update(bytes).digest('hex');this.exe=join(this.dataDir,'desktop-'+hash.slice(0,16)+'.exe');try{await readFile(this.exe);}catch{const compile=join(this.dataDir,'compile.ps1');await writeFile(compile,"param([string]$Source,[string]$Output)\n$ErrorActionPreference='Stop'\nAdd-Type -TypeDefinition ([IO.File]::ReadAllText($Source)) -OutputAssembly $Output -OutputType ConsoleApplication -ReferencedAssemblies @('System.Drawing.dll','System.Windows.Forms.dll','System.dll')\n");await run('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',compile,'-Source',source,'-Output',this.exe],{windowsHide:true,env:{...process.env,PSModulePath:undefined}});}}
 async ensure(id:string){valid(id);if(!this.controls.has(id))this.controls.set(id,'agent');return {id};}
 control(id:string){return this.controls.get(id)||'agent';}
 async setControl(id:string,value:'user'|'agent'){await this.ensure(id);if(value==='user'){if(this.activeUser&&this.activeUser!==id)throw Error('Another Dot panel is controlling this PC.');this.activeUser=id;}else if(this.activeUser===id){this.activeUser=undefined;if(this.child)await this.command('release');}this.controls.set(id,value);}
 async appearance(id:string,_:DesktopAppearance){await this.ensure(id);}
 private launchCapture(){if(this.child)return;if(this.idle){clearTimeout(this.idle);this.idle=undefined;}this.failure='';let buffer=Buffer.alloc(0);const p=spawn(this.exe,[],{windowsHide:true,stdio:['pipe','pipe','pipe']});this.child=p;
  p.stdout!.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.length>=4){const length=buffer.readInt32LE(0);if(length<1||length>8*1024*1024){buffer=Buffer.alloc(0);break;}if(buffer.length<length+4)break;this.latest=Buffer.from(buffer.subarray(4,4+length));buffer=buffer.subarray(4+length);this.emit('frame',this.latest);}});
  let errors='';p.stderr!.on('data',b=>{errors+=b.toString();let end;while((end=errors.indexOf('\n'))>=0){const line=errors.slice(0,end).trim();errors=errors.slice(end+1);const ack=/^(ACK|ERR) (\d+)(.*)$/.exec(line);if(ack){const pending=this.pending.get(Number(ack[2]));if(pending){clearTimeout(pending.timer);this.pending.delete(Number(ack[2]));if(ack[1]==='ACK')pending.resolve();else pending.reject(Error(ack[3].trim()));}}else this.failure=line;}});p.once('error',e=>{this.failure=e.message;});p.once('exit',()=>{for(const pending of this.pending.values()){clearTimeout(pending.timer);pending.reject(Error('PC input helper stopped'));}this.pending.clear();if(this.child===p){this.child=undefined;this.latest=undefined;}});
 }
 private async ready(){if(this.child&&this.latest)return;if(this.starting)return this.starting;this.starting=(async()=>{this.launchCapture();for(let n=0;n<100;n++){if(this.latest)return;if(this.failure)throw Error(this.failure);await new Promise(r=>setTimeout(r,50));}throw Error('PC screenshot unavailable. Windows user session must be unlocked.');})().finally(()=>{this.starting=undefined;});return this.starting;}
 private stopIdle(){if(this.listenerCount('frame')||this.idle)return;this.idle=setTimeout(()=>{this.idle=undefined;if(!this.listenerCount('frame')){this.child?.stdin?.end('stop\n');}},5000);}
 async screenshot(id:string){await this.ensure(id);const {stdout}=await run(this.exe,['--png'],{windowsHide:true,encoding:'buffer',maxBuffer:8*1024*1024});return stdout.toString('base64');}
 async capture(id:string,receive:(jpeg:string)=>void){await this.ensure(id);if(this.idle){clearTimeout(this.idle);this.idle=undefined;}await this.ready();const listener=(b:Buffer)=>receive(b.toString('base64'));this.on('frame',listener);return()=>{this.off('frame',listener);this.stopIdle();};}
 private async command(text:string){await this.ready();const id=++this.seq;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('PC input timed out'));},3000);this.pending.set(id,{resolve,reject,timer});this.child!.stdin!.write(id+'\t'+text+'\n',e=>{if(e){clearTimeout(timer);this.pending.delete(id);reject(e);}});});this.stopIdle();}
 async input(id:string,e:StreamInput,actor:'user'|'agent'='user'){await this.ensure(id);if(actor==='user'&&this.control(id)!=='user')return;if(actor==='agent'&&this.activeUser)throw Error('PC is under user control');if(e.type==='move')await this.command('move '+e.x+' '+e.y);else if(e.type==='wheel')await this.command('wheel '+e.x+' '+e.y);else await this.command(e.type+' '+e.keysym);}
 async execute(p:Record<string,any>,actor:'agent'|'user'='agent'){await this.ensure(p.sessionId);if(actor==='agent'&&this.activeUser&&!['appearance','list','screenshot'].includes(p.action))throw Error('PC is under user control');
  const apps=[{id:'browser',name:'Browser'},{id:'terminal',name:'Terminal'},{id:'files',name:'Files'},{id:'notepad',name:'Notepad'}];
  switch(p.action){case'appearance':await this.appearance(p.sessionId,p.appearance);break;case'list':break;case'screenshot':break;
   case'launch':{const commands:Record<string,[string,string[]]>={browser:['explorer.exe',['https://www.google.com']],terminal:['powershell.exe',['-NoExit','-NoProfile']],files:['explorer.exe',[this.workspace]],notepad:['notepad.exe',[]]};const app=commands[p.app];if(!app)throw Error('Unknown PC app');spawn(app[0],app[1],{cwd:this.workspace,windowsHide:p.app!=='terminal',detached:true,stdio:'ignore'}).unref();break;}
   case'click':if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.button&&![1,2,3].includes(p.button))throw Error('Invalid click');await this.input(p.sessionId,{type:'move',x:p.x,y:p.y},actor);await this.input(p.sessionId,{type:'keydown',keysym:p.button||1},actor);await this.input(p.sessionId,{type:'keyup',keysym:p.button||1},actor);break;
   case'type':if(typeof p.text!=='string'||p.text.length>20000)throw Error('Invalid text');await new Promise(r=>setTimeout(r,60));await this.command('text '+Buffer.from(p.text).toString('base64'));break;
   case'press':{const keys:Record<string,number>={Ctrl:65507,Control:65507,Alt:65513,Shift:65505,Super:65515,Win:65515,Return:65293,Enter:65293,Tab:65289,Escape:65307,BackSpace:65288,Delete:65535,Left:65361,Right:65363,Up:65362,Down:65364};const parts=String(p.key).split('+');const syms=parts.map(k=>keys[k]||(/^F([1-9]|1[0-2])$/.test(k)?65469+Number(k.slice(1)):k.length===1?k.codePointAt(0):0));if(syms.some(k=>!k))throw Error('Unsupported key chord');for(const key of syms){await this.command('keydown '+key);await new Promise(r=>setTimeout(r,8));}for(const key of syms.reverse())await this.command('keyup '+key);break;}
   default:throw Error('Unsupported PC desktop action');}
  return {sessionId:p.sessionId,width:1280,height:800,control:this.control(p.sessionId),environment:'connected-pc',apps,windows:[],...p.action==='list'||p.action==='appearance'?{}:{screenshot:await this.screenshot(p.sessionId)}};
 }
 async close(){if(this.idle)clearTimeout(this.idle);this.removeAllListeners('frame');const p=this.child;if(p){p.stdin?.end('stop\n');await new Promise<void>(r=>{const timeout=setTimeout(()=>{p.kill();r();},2000);p.once('exit',()=>{clearTimeout(timeout);r();});});}this.controls.clear();this.activeUser=undefined;}
}
