import { voicePrefix, voiceVocabulary } from './voice-text.js';
import Fastify from 'fastify';
import multipart from '@fastify/multipart';
import websocket from '@fastify/websocket';
import { z } from 'zod';
import { readFileSync } from 'node:fs';
import { readFile, stat, realpath, mkdir } from 'node:fs/promises';
import { join, relative, isAbsolute } from 'node:path';
import { zstdDecompressSync, gunzipSync, brotliDecompressSync, inflateSync } from 'node:zlib';
import type { Settings, RecordStore, TaskRunner, RuntimeEvent, RunInput, RunnerHooks } from '@dots/contracts';
import { loadConfig, type ServerConfig } from './config.js';
import { SqliteStore } from './storage.js';
import { AuthService, bearer } from './auth.js';
import { OrbitRuntime, AppServerRunner } from './runtime/index.js';
import { IntegrationService } from './integrations/index.js';
import { WorkerBroker, RoutingRunner } from './workers.js';
import { BlobStore } from './blobs.js';
import { ExternalEvents } from './events.js';
import { DotTools, toolContext } from './tools.js';
import { registerNative, computerAppearance } from './native.js';
import {dotBrowserSession} from './browser-session.js';
import { importLegacy } from './migrate.js';
import {modelProxy} from './model-proxy.js';
import {ProviderService,isGptModel,DEFAULT_PROVIDER_ID} from './providers.js';
import {SecretVault} from './integrations/security.js';
import {gatewayKey} from './config.js';
import {RpcClient} from './runtime/index.js';
import {HostConnections} from './connections.js';
import {NetworkService} from './network.js';
import {ComputerTransport} from './computer-transport.js';
import {ComputerSetup} from './computer-setup.js';
/** Codex istek gövdesini zstd ile sıkıştırıp gönderir; JSON ayrıştırmadan önce açılır. */
const decodeBody=(body:Buffer,encoding:unknown):Buffer=>{switch(String(encoding||'').toLowerCase()){case 'zstd':return zstdDecompressSync(body);case 'gzip':case 'x-gzip':return gunzipSync(body);case 'br':return brotliDecompressSync(body);case 'deflate':return inflateSync(body);default:return body;}};
const object=z.record(z.string(),z.unknown());
const dotSchema=z.object({name:z.string().trim().min(1).max(120),model:z.string().nullable().optional(),reasoningEffort:z.string().nullable().optional(),serviceTier:z.string().nullable().optional(),computerId:z.string().nullable().optional(),instructions:z.string().max(200000).optional(),avatarUrl:z.string().nullable().optional(),avatarManifest:object.nullable().optional()});
const taskSchema=z.object({dotId:z.string(),input:z.string().trim().min(1).max(200000),title:z.string().max(200).optional(),parentTaskId:z.string().nullable().optional(),threadId:z.string().nullable().optional(),computerId:z.string().nullable().optional(),model:z.string().nullable().optional(),reasoningEffort:z.string().nullable().optional(),serviceTier:z.string().nullable().optional(),cwd:z.string().nullable().optional(),source:z.enum(['chat','schedule','delegation','manual','channel','proactive']).optional(),attachments:z.array(z.object({id:z.string(),name:z.string(),mimeType:z.string(),size:z.number(),path:z.string().optional()})).optional()});
const memorySchema=z.object({dotId:z.string(),title:z.string().trim().min(1).max(300),content:z.string().trim().min(1).max(200000),tags:z.array(z.string().max(100)).optional()});
const scheduleSchema=z.object({dotId:z.string(),title:z.string().trim().min(1),prompt:z.string().trim().min(1).max(200000),kind:z.enum(['interval','once','cron','rrule']),rrule:z.string().optional(),enabled:z.boolean().optional(),intervalSeconds:z.number().positive().nullable().optional(),cron:z.string().nullable().optional(),timezone:z.string().optional(),nextRunAt:z.string().nullable().optional(),computerId:z.string().nullable().optional(),proactive:z.boolean().optional()});
const connectorSchema=z.object({kind:z.enum(['slack','teams','email','mcp','webhook','github']),name:z.string().trim().min(1),config:object,scopes:z.array(z.string()).optional(),enabled:z.boolean().optional()});
const idOf=(req:any)=>String(req.params.id);
const filter=(req:any)=>({dotId:typeof req.query.dotId==='string'?req.query.dotId:undefined,taskId:typeof req.query.taskId==='string'?req.query.taskId:undefined,status:typeof req.query.status==='string'?req.query.status:undefined});
const list=<T>(items:T[])=>({items,cursor:null});
export async function buildServer(options:{config?:ServerConfig;store?:RecordStore;runner?:TaskRunner;logger?:boolean}={}){
  const config=options.config||loadConfig(),store=options.store||new SqliteStore(join(config.dataDir,'dots.sqlite'));
  const network=new NetworkService({host:config.host,port:config.port}),connections=new HostConnections(store,new SecretVault(config.signingKey),{url:'http://127.0.0.1:'+config.port,adminKey:config.adminKey});
  const computerTransport=new ComputerTransport(store,new SecretVault(config.signingKey));
  const computerSetup=new ComputerSetup(store);
  await mkdir(join(config.dataDir,'workspaces'),{recursive:true});
  const app=Fastify({bodyLimit:48*1024*1024,logger:options.logger?{redact:['req.headers.authorization','req.headers.cookie','req.headers.sec-websocket-protocol'],serializers:{req:(req:any)=>({method:req.method,url:req.url?.split('?')[0]})}}:false,...config.tlsCert&&config.tlsKey?{https:{cert:readFileSync(config.tlsCert),key:readFileSync(config.tlsKey)}}:{}});
  await app.register(multipart,{limits:{fileSize:32*1024*1024,files:10}});await app.register(websocket,{options:{maxPayload:32*1024*1024}});
  app.removeContentTypeParser('application/json');app.addContentTypeParser('application/json',{parseAs:'buffer'},(req,body,done)=>{(req as any).rawBody=body;try{const plain=decodeBody(body as Buffer,req.headers['content-encoding']);done(null,plain.length?JSON.parse(plain.toString()):undefined);}catch(e){done(Object.assign(e as Error,{statusCode:400}));}});
  app.addContentTypeParser('application/x-www-form-urlencoded',{parseAs:'string'},(req,body,done)=>done(null,Object.fromEntries(new URLSearchParams(body as string))));
  app.addContentTypeParser('application/sdp',{parseAs:'string',bodyLimit:65536},(req,body,done)=>done(null,body));
  app.setErrorHandler((error,req,reply)=>{if(!(error instanceof z.ZodError)&&!(typeof (error as any).statusCode==='number'&&(error as any).statusCode<500))req.log.error({err:{message:(error as Error).message,stack:(error as Error).stack?.split('\\n').slice(0,6)}},'request failed');const status=error instanceof z.ZodError?400:typeof (error as any).statusCode==='number'?(error as any).statusCode:500;reply.code(status).send({error:status===500?'Internal server error':(error as Error).message,...error instanceof z.ZodError?{issues:error.issues.map(i=>({path:i.path,message:i.message}))}:{}});});
  const auth=new AuthService(config.signingKey,config.adminKey,store),external=new ExternalEvents(store),blobs=new BlobStore(join(config.dataDir,'files'),store);
  const settings=()=>({autoApproveExecution:true,...store.get<Settings&{id:string}>('settings','owner')||{id:'owner',appServerUrl:config.appServerUrl,model:config.model,reasoningEffort:config.reasoningEffort,serviceTier:config.serviceTier,maxParallelTasks:3,proactiveEnabled:false}});
  const providers=new ProviderService(store,{vault:new SecretVault(config.signingKey),fallback:{baseUrl:config.modelBaseUrl,apiKey:config.modelApiKey},activeId:()=>(settings() as any).activeProviderId??null});
  const tierFor=(model:string|null|undefined,tier:string|null|undefined,explicit:boolean)=>{if(!tier||!model||isGptModel(model))return tier??null;if(explicit)throw Object.assign(new Error('Hızlı mod yalnızca GPT modellerinde kullanılabilir'),{statusCode:400});return null;};
  const providerBody=z.object({name:z.string().trim().min(1).max(120),baseUrl:z.string().min(1).max(2000),apiKey:z.string().max(4096).nullable().optional(),apiFormat:z.enum(['responses','chat']),manualModels:z.array(z.string().trim().min(1).max(300)).max(200).optional()});
  const workers:WorkerBroker=new WorkerBroker(store,auth,{onlineMs:config.workerOnlineMs,emit:(t,d)=>external.publish(t,d),onToolCall:(name,args,input,signal):Promise<unknown>=>tools.call(name,args,input,signal)});
  let runtime:OrbitRuntime,integrations:IntegrationService;const tools:DotTools=new DotTools(()=>runtime,()=>integrations,workers,store,blobs);
  const localRunner:TaskRunner=options.runner||{run:(input,hooks,signal)=>new AppServerRunner({url:settings().appServerUrl,model:settings().model||undefined,reasoningEffort:settings().reasoningEffort,serviceTier:settings().serviceTier||undefined,cwd:join(config.dataDir,'workspaces'),attachmentRoots:[blobs.directory],tools:i=>tools.list(i),onToolCall:(name,args,i,signal)=>tools.call(name,args,i,signal),threadHasTools:id=>store.get<any>('thread_tool_versions',id)?.version===DotTools.VERSION,onToolsThread:id=>store.put('thread_tool_versions',{id,version:DotTools.VERSION}),contextHistory:i=>runtime.listMessages(i.dot.id).slice(-80).map(m=>`${m.role}: ${m.text}`).join('\n\n')}).run(input,hooks,signal)};
  const routing=new RoutingRunner(localRunner,workers,input=>tools.list(input));
  const runner:TaskRunner={run:async(input,hooks,signal)=>{
    input={...input,fullAccess:settings().autoApproveExecution===true&&input.task.source!=='proactive'};
    const manual=store.get<{id:string;connectorId?:string;name?:string;args?:Record<string,unknown>;outboxId?:string}>('manual_tool_calls',input.task.id);
    if(manual){const text=await toolContext.run(input,async()=>JSON.stringify(manual.outboxId?await integrations.deliverReply(manual.outboxId):await integrations.call(manual.connectorId!,manual.name!,manual.args!)));return {text,threadId:input.task.threadId||'tool:'+input.task.id,turnId:null};}
    if(store.get('voice_tasks',input.task.id)){
      const voiceInput={...input,task:{...input.task,input:voicePrefix(input.dot.name,runtime.listMessages(input.dot.id),input.task.id,!input.task.threadId)+input.task.input}};
      try{return await routing.run(voiceInput,hooks,signal);}
      catch(error){if(input.task.reasoningEffort&&/reasoning|effort/i.test(String((error as Error)?.message)))return routing.run({...voiceInput,task:{...voiceInput.task,reasoningEffort:null}},hooks,signal);throw error;}
    }
    return routing.run(input,hooks,signal);
  }};
  runtime=new OrbitRuntime(store,runner,{settings,defaultCwd:join(config.dataDir,'workspaces'),defaultComputerId:()=>store.get<any>('settings','owner')?.defaultComputerId||workers.list().find(c=>c.state==='online'&&c.platform==='win32')?.id||null});
  integrations=new IntegrationService(store,{encryptionKey:config.signingKey,inbound:async(dotId,text,channel,requestId)=>runtime.submitMessage(dotId,{text,channel,requestId}),emit:(t,d)=>external.publish(t,d),authorizeSend:async(c,name,args)=>{const input=toolContext.getStore();if(!input||input.task.source==='proactive')return false;return runtime.requestApproval(input.task.id,{kind:'external_send',title:`${c.name}: ${name}`,detail:JSON.stringify(args),request:{connectorId:c.id,tool:name,arguments:args}});}});
  const requireAdmin=async(req:any,reply:any)=>{if(!auth.verify(bearer(req.headers.authorization),['admin']))return reply.code(401).send({error:'Authentication required'});};
  const requireWorker=async(req:any,reply:any)=>{const c=auth.verify(bearer(req.headers.authorization),['worker']);if(!c)return reply.code(401).send({error:'Worker authentication required'});req.computerId=c.sub;};
  app.get('/health',async()=>({ok:true,version:'0.1.0',connectionProtocol:1}));
  const loginAttempts=new Map<string,{count:number;until:number}>();
  app.post('/api/v1/session',async(req,reply)=>{const prior=loginAttempts.get(req.ip),attempts=prior&&prior.until>Date.now()?prior:{count:0,until:Date.now()+60000};if(attempts.count>=10)return reply.code(429).send({error:'Too many login attempts'});const body=z.object({token:z.string().max(500)}).parse(req.body),session=auth.login(body.token);if(session){loginAttempts.delete(req.ip);return session;}attempts.count++;if(loginAttempts.size>1000)loginAttempts.clear();loginAttempts.set(req.ip,attempts);return reply.code(401).send({error:'Invalid access key'});});
  await app.register(async admin=>{
    admin.addHook('preHandler',requireAdmin);
    admin.get('/overview',async()=>({dots:runtime.listDots(),tasks:runtime.listTasks(),activity:runtime.listActivity().slice(-100),outputs:runtime.listOutputs(),computers:workers.list(),pendingApprovals:runtime.listApprovals().filter(a=>a.status==='pending').length,settings:settings()}));
    admin.get('/settings',async()=>settings());
    admin.get('/computer-transport',async()=>computerTransport.list());
    admin.put('/computer-transport',async req=>computerTransport.save(z.object({items:z.array(z.object({id:z.string().optional(),urls:z.array(z.string().max(2048)).min(1).max(8),username:z.string().max(1024).optional(),credential:z.string().max(2048).optional()})).max(8)}).parse(req.body).items));
    admin.get('/connections',async()=>connections.status());
    admin.get('/connections/setup',async()=>({items:computerSetup.status()}));
    admin.post('/connections/setup',async req=>computerSetup.queue(z.object({kind:z.enum(['debian','custom']),distribution:z.string().max(60),imagePath:z.string().max(3000).optional(),sha256:z.string().max(64).optional()}).parse(req.body)));
    admin.post('/connections/setup-next',async()=>computerSetup.next());
    admin.post('/connections/setup/:id',async req=>computerSetup.finish(idOf(req),z.object({status:z.enum(['completed','failed']),error:z.string().max(2000).nullable()}).parse(req.body)));
    admin.post('/connections',async req=>connections.create(z.object({name:z.string().trim().min(1).max(120),serverUrl:z.string().max(2000),adminKey:z.string().min(1).max(4096)}).parse(req.body)));
    admin.patch('/connections/:id',async req=>connections.update(idOf(req),z.object({name:z.string().trim().min(1).max(120).optional(),adminKey:z.string().min(1).max(4096).optional(),options:z.object({nativeEnabled:z.boolean().optional(),workerEnabled:z.boolean().optional(),linuxEnabled:z.boolean().optional(),gatewayPort:z.number().int().optional(),workerRoots:z.array(z.string().max(2000)).max(32).optional(),computerMode:z.enum(['pc','linux','host']).optional(),hostComputerId:z.string().max(100).nullable().optional()}).optional()}).parse(req.body)));
    admin.delete('/connections/:id',async req=>connections.remove(idOf(req)));
    admin.post('/connections/:id/test',async req=>connections.test(idOf(req)));
    admin.post('/connections/:id/activate',async req=>connections.activate(idOf(req)));
    admin.get('/connections/runtime-plan',async()=>connections.plan());
    admin.get('/connections/:id/computers',async req=>connections.computers(idOf(req)));
    admin.get('/network',async()=>network.status());
    admin.post('/network/tailscale',async req=>network.setExposed(z.object({enabled:z.boolean()}).parse(req.body).enabled));
    admin.post('/connections/bootstrap',async req=>{connections.bootstrap(req.body as any);return {ok:true};});
    admin.post('/connections/heartbeat',async req=>connections.heartbeat(z.object({profileId:z.string(),revision:z.string(),nativeReady:z.boolean(),workerReady:z.boolean(),linuxReady:z.boolean(),error:z.string().nullable()}).parse(req.body)));
    admin.patch('/settings',async req=>{const patch=z.object({appServerUrl:z.string().url().optional(),model:z.string().nullable().optional(),reasoningEffort:z.string().optional(),serviceTier:z.string().nullable().optional(),activeProviderId:z.string().nullable().optional(),maxParallelTasks:z.number().int().min(1).max(32).optional(),proactiveEnabled:z.boolean().optional(),autoApproveExecution:z.boolean().optional(),defaultComputerId:z.string().nullable().optional()}).parse(req.body);if(patch.activeProviderId)providers.get(patch.activeProviderId);if(patch.defaultComputerId)workers.get(patch.defaultComputerId);const next:any={...settings(),...patch};next.serviceTier=tierFor(next.model,next.serviceTier,!!patch.serviceTier);store.put('settings',next);if(patch.autoApproveExecution!==undefined)runtime.applyExecutionApprovalSetting();external.publish('settings.updated',{});return next;});
    admin.get('/providers',async()=>({items:providers.list(),activeProviderId:providers.activeId()}));
    admin.post('/providers',async req=>providers.create(providerBody.parse(req.body)));
    admin.patch('/providers/:id',async req=>providers.update(idOf(req),providerBody.partial().parse(req.body)));
    admin.delete('/providers/:id',async req=>{const id=idOf(req),wasActive=providers.activeId()===id,deleted=providers.remove(id);if(wasActive)store.put('settings',{...settings(),activeProviderId:DEFAULT_PROVIDER_ID,model:null,serviceTier:null});return {deleted};});
    admin.post('/providers/:id/refresh-models',async req=>providers.refreshModels(idOf(req)));
    admin.post('/providers/:id/test',async req=>providers.test(idOf(req),z.object({model:z.string().max(300).optional()}).parse(req.body||{}).model));
    admin.get('/models',async req=>providers.models(typeof (req.query as any).providerId==='string'?(req.query as any).providerId:undefined));
    admin.get('/dots',async()=>list(runtime.listDots()));
    admin.post('/dots',async req=>{const p=dotSchema.parse(req.body),s=settings();return runtime.createDot({...p,model:p.model??null,reasoningEffort:p.reasoningEffort??null,serviceTier:tierFor(p.model??s.model,p.serviceTier,!!p.serviceTier)});});
    admin.get('/dots/:id',async req=>runtime.getDot(idOf(req)));
    admin.patch('/dots/:id',async req=>{const p=dotSchema.partial().parse(req.body),cur=runtime.getDot(idOf(req)),model=p.model!==undefined?p.model:cur.model,serviceTier=p.serviceTier!==undefined?tierFor(model,p.serviceTier,!!p.serviceTier):p.model!==undefined?tierFor(model,cur.serviceTier,false):undefined;return runtime.updateDot(idOf(req),{...p,...serviceTier!==undefined?{serviceTier}:{}});});
    admin.delete('/dots/:id',async req=>({deleted:runtime.deleteDot(idOf(req))}));
    admin.post('/dots/:id/pause',async req=>runtime.pauseDot(idOf(req)));admin.post('/dots/:id/resume',async req=>runtime.resumeDot(idOf(req)));
    admin.get('/dots/:id/messages',async req=>list(runtime.listMessages(idOf(req))));
    admin.post('/dots/:id/messages',async req=>{const p=z.object({text:z.string().trim().min(1).max(200000),requestId:z.string().max(200).optional(),channel:z.string().optional(),computerId:z.string().nullable().optional(),attachments:taskSchema.shape.attachments}).parse(req.body);return runtime.submitMessage(idOf(req),{...p,attachments:p.attachments?.map(a=>blobs.forDot(a.id,idOf(req)))});});
    admin.post('/dots/:id/attachments',async req=>{runtime.getDot(idOf(req));const part=await req.file();if(!part)throw Object.assign(new Error('File required'),{statusCode:400});return blobs.put(await part.toBuffer(),part.filename,part.mimetype,idOf(req));});
    admin.get('/tasks',async req=>list(runtime.listTasks(filter(req) as any)));
    admin.post('/tasks',async req=>{const p=taskSchema.parse(req.body);tierFor(p.model??runtime.getDot(p.dotId).model,p.serviceTier,!!p.serviceTier);return runtime.createTask({...p,attachments:p.attachments?.map(a=>blobs.forDot(a.id,p.dotId))});});
    admin.get('/tasks/:id',async req=>runtime.getTask(idOf(req)));admin.post('/tasks/:id/cancel',async req=>runtime.cancelTask(idOf(req)));admin.post('/tasks/:id/retry',async req=>runtime.retryTask(idOf(req)));
    admin.post('/tasks/:id/continue',async req=>runtime.continueTask(idOf(req),z.object({input:z.string().trim().min(1).max(200000),title:z.string().optional()}).parse(req.body)));
    admin.get('/threads/attached',async req=>list(runtime.listAttachedThreads(filter(req).dotId)));
    admin.post('/threads/attach',async req=>{const body=z.object({dotId:z.string(),threadId:z.string(),computerId:z.string().nullable().optional()}).parse(req.body);runtime.getDot(body.dotId);let result:any;if(body.computerId)result=await workers.execute(body.computerId,'rpc',{request:{method:'thread/read',params:{threadId:body.threadId,includeTurns:false}}});else{const rpc=new RpcClient({url:settings().appServerUrl});try{await rpc.connect();await rpc.request('initialize',{clientInfo:{name:'dots_attach',version:'0.1.0'},capabilities:{experimentalApi:true}});rpc.notify('initialized');result=await rpc.request('thread/read',{threadId:body.threadId,includeTurns:false});}finally{rpc.close();}}if(result.thread?.id!==body.threadId)throw Object.assign(new Error('Thread read did not match the requested conversation'),{statusCode:502});return runtime.attachThread(body.dotId,{threadId:body.threadId,computerId:body.computerId||null,title:result.thread.name||result.thread.preview||null,model:result.thread.model||null,reasoningEffort:result.thread.reasoningEffort||null,serviceTier:null,cwd:result.thread.cwd||null});});
    admin.post('/threads/:id/continue',async req=>{const body=z.object({dotId:z.string(),input:z.string().trim().min(1).max(200000),title:z.string().optional()}).parse(req.body);return runtime.continueThread(body.dotId,idOf(req),body);});
    admin.post('/tasks/:id/delegate',async req=>runtime.delegateTask(idOf(req),z.object({input:z.string().trim().min(1),title:z.string().optional(),computerId:z.string().nullable().optional()}).parse(req.body)));
    admin.get('/activity',async req=>list(runtime.listActivity(filter(req))));admin.get('/outputs',async req=>list(runtime.listOutputs(filter(req))));
    admin.get('/outputs/:id/content',async(req,reply)=>{const o=runtime.getOutput(idOf(req));let bytes:Buffer;
      if(o.computerId){const r=await workers.execute(o.computerId,'filesystem',{action:'read',path:o.path});bytes=Buffer.from(r.data,'base64');}
      else{const base=await realpath(join(config.dataDir,'workspaces')),p=await realpath(o.path),rel=relative(base,p);if(rel.startsWith('..')||isAbsolute(rel))throw Object.assign(new Error('Output is outside server workspaces'),{statusCode:403});if((await stat(p)).size>32*1024*1024)throw Object.assign(new Error('Output too large'),{statusCode:413});bytes=await readFile(p);}
      return reply.type(o.mimeType).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(o.name)}`).send(bytes);});
    admin.get('/memories',async req=>list(runtime.listMemories(filter(req).dotId)));admin.post('/memories',async req=>runtime.createMemory(memorySchema.parse(req.body)));admin.patch('/memories/:id',async req=>runtime.updateMemory(idOf(req),memorySchema.omit({dotId:true}).partial().parse(req.body)));admin.delete('/memories/:id',async req=>({deleted:runtime.deleteMemory(idOf(req))}));
    admin.get('/schedules',async req=>list(runtime.listSchedules(filter(req).dotId)));admin.post('/schedules',async req=>runtime.createSchedule(scheduleSchema.parse(req.body)));admin.patch('/schedules/:id',async req=>runtime.updateSchedule(idOf(req),scheduleSchema.omit({dotId:true}).partial().parse(req.body)));admin.delete('/schedules/:id',async req=>({deleted:runtime.deleteSchedule(idOf(req))}));admin.post('/schedules/:id/run',async req=>runtime.runSchedule(idOf(req)));
    admin.get('/approvals',async req=>list(runtime.listApprovals(filter(req))));admin.post('/approvals/:id/resolve',async req=>runtime.resolveApproval(idOf(req),z.object({approved:z.boolean(),resolution:object.optional()}).parse(req.body)));
    admin.get('/computers',async()=>list(workers.list()));admin.post('/computers/enrollment',async req=>{const e=auth.enroll('worker'),url=`${req.protocol}://${req.headers.host}`;return {...e,command:`npm run dev:worker -- --server "${url}" --enrollment "${e.token}" --root "<workspace>"`};});admin.delete('/computers/:id',async req=>{workers.revoke(idOf(req));return {deleted:true};});
    admin.patch('/computers/:id',async req=>{const p=z.object({roots:z.array(z.string().min(1)).min(1).max(32)}).parse(req.body),c=workers.get(idOf(req));store.put('computers',{...c,roots:p.roots});return {...c,roots:p.roots};});
    admin.post('/computers/:id/browser',async req=>{const body=z.object({action:z.enum(['open','navigate','click','type','press','screenshot','takeover','release','close']),sessionId:z.string().optional(),url:z.string().optional(),x:z.number().optional(),y:z.number().optional(),text:z.string().optional(),key:z.string().optional()}).parse(req.body);return workers.queue(idOf(req),'browser',{...body,actor:'user'});});
    admin.post('/computers/:id/desktop',async req=>{const b=z.object({dotId:z.string(),action:z.enum(['list','launch','screenshot','click','type','press']),app:z.string().optional(),x:z.number().optional(),y:z.number().optional(),button:z.number().optional(),text:z.string().optional(),key:z.string().optional()}).parse(req.body);const dot=runtime.getDot(b.dotId),session=dotBrowserSession(store,dot.id,idOf(req));await workers.execute(idOf(req),'desktop',{action:'appearance',sessionId:session.sessionId,dotId:dot.id,appearance:await computerAppearance({config,providers,store,runtime,auth,blobs,workers,integrations,external},dot),actor:'agent'});return workers.execute(idOf(req),'desktop',{...b,sessionId:session.sessionId,actor:'agent'});});
    admin.get('/browser/jobs/:id',async req=>workers.getJob(idOf(req)));admin.get('/browser/screenshots/:id',async(req,reply)=>reply.type('image/png').send(await blobs.read(idOf(req))));
    admin.get('/connectors',async()=>list(integrations.list()));admin.post('/connectors',async req=>integrations.create(connectorSchema.parse(req.body)));admin.patch('/connectors/:id',async req=>integrations.update(idOf(req),connectorSchema.omit({kind:true}).partial().parse(req.body)));admin.delete('/connectors/:id',async req=>({deleted:integrations.delete(idOf(req))}));admin.post('/connectors/:id/test',async req=>integrations.test(idOf(req)));admin.get('/connectors/:id/tools',async req=>list(await integrations.tools(idOf(req))));
    admin.get('/connectors/outbox',async()=>list(integrations.listOutbox()));
    admin.post('/connectors/outbox/:id/retry',async req=>{const outbox=integrations.listOutbox().find(o=>o.id===idOf(req));if(!outbox)throw Object.assign(new Error('Reply not found'),{statusCode:404});const parent=runtime.getTask(outbox.taskId),task=runtime.createTask({dotId:parent.dotId,title:'Reply delivery',input:'Deliver the reviewed channel reply',source:'manual'});store.put('manual_tool_calls',{id:task.id,outboxId:outbox.id});return {taskId:task.id};});
    admin.post('/connectors/:id/tools/:name/call',async req=>{const body=z.object({arguments:object}).parse(req.body);const dot=runtime.listDots()[0];if(!dot)throw Object.assign(new Error('Create a dot first'),{statusCode:409});const name=String((req.params as any).name),task=runtime.createTask({dotId:dot.id,title:integrations.get(idOf(req)).name+': '+name,input:JSON.stringify(body.arguments),source:'manual'});store.put('manual_tool_calls',{id:task.id,connectorId:idOf(req),name,args:body.arguments});return {taskId:task.id,status:task.status};});
    admin.post('/connectors/:id/poll',async req=>integrations.pollEmail(idOf(req)));
    admin.get('/voice/settings',async()=>integrations.getVoiceSettings());admin.patch('/voice/settings',async req=>integrations.updateVoiceSettings(object.parse(req.body)));
    admin.post('/voice/transcribe',async req=>{const file=await req.file();if(!file)throw Object.assign(new Error('Audio required'),{statusCode:400});return integrations.transcribe(await file.toBuffer(),file.filename,file.mimetype,voiceVocabulary(runtime));});admin.post('/voice/speak',async(req,reply)=>{const b=z.object({text:z.string().trim().min(1).max(4096),voice:z.string().optional()}).parse(req.body),r=await integrations.speak(b.text,b.voice);return reply.type(r.mimeType).send(r.audio);});
    admin.post('/clients/enrollment',async()=>auth.enroll('client'));
    admin.post('/migration/legacy',async req=>importLegacy(z.object({directory:z.string().min(1)}).parse(req.body).directory,store,blobs));
    admin.get('/events',async(req,reply)=>{reply.hijack();reply.raw.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});reply.raw.flushHeaders();let last=String(req.headers['last-event-id']||'');const write=(e:RuntimeEvent)=>{if(e.id<=last)return;last=e.id;reply.raw.write(`id: ${e.id}\nevent: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`);};for(const e of runtime.replay(last))write(e);const off=runtime.subscribe(write);external.on('event',write);const keep=setInterval(()=>reply.raw.write(': heartbeat\n\n'),15000);reply.raw.on('close',()=>{off();external.off('event',write);clearInterval(keep);});});
  },{prefix:'/api/v1'});
  app.post('/client/enroll',async(req,reply)=>{const b=z.object({token:z.string()}).parse(req.body),c=auth.consume(b.token,'enroll-client');if(!c)return reply.code(401).send({error:'Invalid enrollment token'});store.put('clients',{id:c.sub,createdAt:new Date().toISOString()});return {clientId:c.sub,tokens:auth.nativeTokens(c.sub)};});
  app.post('/integrations/:id/webhook',async(req,reply)=>{const r=await integrations.webhook(idOf(req),req.headers,(req as any).rawBody||Buffer.alloc(0));return reply.code(r.statusCode).send(r.body);});
  app.post('/worker/register',async req=>workers.register(z.object({token:z.string(),name:z.string(),platform:z.string(),roots:z.array(z.string()),capabilities:z.array(z.string())}).parse(req.body)));
  await app.register(async worker=>{worker.addHook('preHandler',requireWorker);
    worker.post('/describe',async req=>{const p=z.object({roots:z.array(z.string()).min(1).max(32),capabilities:z.array(z.enum(['codex','browser','filesystem','desktop'])).max(4)}).parse(req.body);const c=workers.get((req as any).computerId);store.put('computers',{...c,...p,lastSeenAt:new Date().toISOString(),state:'online'});return {ok:true};});
    worker.get('/status',async req=>workers.get((req as any).computerId));
    worker.all('/model/:endpoint',async(req,reply)=>{const p=(req.params as any).endpoint;if(p==='responses'&&!workers.executingCodex((req as any).computerId))return reply.code(403).send({error:'An active assigned Codex job is required for inference'});return modelProxy(req,reply,providers,p);});
    worker.post('/heartbeat',async req=>{const body=z.object({activeJobIds:z.array(z.string()).optional()}).parse(req.body||{});workers.heartbeat((req as any).computerId,body.activeJobIds);return {ok:true,activeJobs:workers.active((req as any).computerId)};});
    worker.get('/jobs/next',async(req,reply)=>workers.next((req as any).computerId)||reply.code(204).send());
    worker.post('/jobs/:id/events',async req=>workers.event((req as any).computerId,idOf(req),z.object({type:z.string(),data:z.unknown()}).parse(req.body)));
    worker.post('/jobs/:id/result',async req=>{const b=z.object({result:z.unknown().optional(),error:z.string().optional()}).parse(req.body);let result:any=b.result;
      if(result?.screenshot){const image=await blobs.put(Buffer.from(result.screenshot,'base64'),'browser.png','image/png');result={...result,screenshotId:image.id};delete result.screenshot;}
      workers.finish((req as any).computerId,idOf(req),result,b.error);return {ok:true};});
    worker.get('/attachments/:id',async(req,reply)=>{const a=blobs.get(idOf(req));return reply.type(a.mimeType).send(await blobs.read(a.id));});
  },{prefix:'/worker'});
  app.all('/model-gateway/:endpoint',async(req,reply)=>{if(!auth.equals(bearer(req.headers.authorization)||'',gatewayKey(config.signingKey)))return reply.code(401).send({error:'Model gateway key required'});return modelProxy(req,reply,providers,(req.params as any).endpoint);});
  await registerNative(app,{config,providers,store,runtime,auth,blobs,workers,integrations,external});
  const repliesOff=runtime.subscribe(event=>{if(event.type!=='task.updated')return;const task=event.data.task as any;if(task?.status!=='completed'||!task.result||store.get('manual_tool_calls',task.id))return;void integrations.enqueueReply(task.id,task.result).then(outbox=>{if(!outbox||outbox.status!=='approval_required'||store.get('outbox_tasks',outbox.id))return;const delivery=runtime.createTask({dotId:task.dotId,title:'Reply delivery',input:'Review and deliver the channel reply',source:'manual'});store.put('manual_tool_calls',{id:delivery.id,outboxId:outbox.id});store.put('outbox_tasks',{id:outbox.id,taskId:delivery.id});}).catch(()=>runtime.activity(task.dotId,task.id,'channel.reply_failed','Reply could not be queued'));});
  app.addHook('onClose',async()=>{repliesOff();const closing=integrations.stop();workers.close();await runtime.stop();await closing;if(store instanceof SqliteStore)store.close();});
  return {app,config,providers,store,auth,runtime,workers,integrations,blobs,external,settings};
}
