export function browserViewerPage(config:{token:string;dotId:string;computerId:string;name:string;sessionId:string},nonce:string){
  const bootstrap=JSON.stringify(config).replaceAll('<','\\u003c');
  return `<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Dot tarayıcısı</title>
<style>html{color-scheme:dark;font:14px system-ui;background:#161b28;color:#e5ebf7}body{margin:0;padding:14px}header{display:flex;align-items:center;gap:10px;margin-bottom:12px}strong{flex:1}form,.controls{display:flex;gap:8px;margin:8px 0}input{min-width:0;flex:1}button,input,select{font:inherit;border:1px solid #465572;border-radius:8px;padding:8px;background:#222d42;color:inherit}button{cursor:pointer}button:disabled{opacity:.4}#viewport{border-radius:8px;overflow:hidden;background:#101622;min-height:240px}img{width:100%;display:block}#empty{min-height:240px;display:grid;align-content:center;justify-items:center;padding:24px;text-align:center;gap:10px;color:#abbad2}#empty b{color:#e5ebf7;font-size:16px}#screen[hidden],#empty[hidden]{display:none}#status{min-height:20px;color:#abbad2}small{display:block;margin-top:8px;color:#abbad2}@media(max-width:520px){header,.controls{flex-wrap:wrap}header strong{flex-basis:100%}}</style>
<body><header><strong id="name"></strong><button id="take" disabled>Kontrolü devral</button><button id="release" disabled>Dot'a geri ver</button></header>
<form id="navigate"><input id="url" type="url" placeholder="https://…" aria-label="Web adresi" required><button id="go" disabled>Aç</button></form>
<div class="controls"><input id="text" placeholder="Odaklanan alana yaz" aria-label="Yazılacak metin"><button id="type" disabled>Yaz</button><select id="key"><option>Enter</option><option>Tab</option><option>Control+A</option><option>Escape</option><option>Backspace</option><option>ArrowDown</option></select><button id="press" disabled>Tuş</button><button id="shot" disabled>Yenile</button></div>
<p id="status" role="status">Tarayıcıya bağlanılıyor…</p><div id="viewport"><div id="empty"><b id="empty-title">Tarayıcıya bağlanılıyor…</b><span id="empty-detail">Dot'un mevcut oturumu yükleniyor.</span></div><img id="screen" hidden alt="Dot'un tarayıcısı"></div>
<small>Dot ile aynı tarayıcı oturumu. Kontrolü devralınca Dot'un tarayıcı işlemleri durur.</small>
<script nonce="${nonce}">
const cfg=${bootstrap};let sessionId=cfg.sessionId,busy=false,ready=false,control='agent',objectUrl=null,width=1280,height=800;const byId=id=>document.getElementById(id);byId('name').textContent=cfg.name;
function controls(){for(const id of ['go','take'])byId(id).disabled=!ready||busy;byId('shot').disabled=busy;for(const id of ['type','press','release'])byId(id).disabled=!ready||busy||control!=='user';}
function empty(title,detail){byId('screen').hidden=true;byId('empty').hidden=false;byId('empty-title').textContent=title;byId('empty-detail').textContent=detail;}
async function json(response){const data=await response.json();if(!response.ok)throw new Error(data.error||data.detail||'İşlem reddedildi');return data;}
const request=async(action,extra={},quiet=false)=>{if(busy)return;busy=true;controls();if(!quiet)byId('status').textContent='İşlem sürüyor…';try{
 const initial=await json(await fetch('./viewer/control?thread_id='+encodeURIComponent(new URL(location.href).searchParams.get('thread_id')||''),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:cfg.token,action,sessionId,...extra})}));
 let job=initial;for(let i=0;i<160;i++){job=await json(await fetch('./viewer/jobs/'+encodeURIComponent(initial.id)+'?t='+encodeURIComponent(cfg.token)));if(job.status==='completed')break;if(['failed','cancelled'].includes(job.status))throw new Error(job.error||'İşlem başarısız');await new Promise(resolve=>setTimeout(resolve,250));}
 if(job.status!=='completed')throw new Error('Bilgisayardan sonuç alınamadı');const result=job.result;sessionId=result.sessionId;control=result.control;ready=true;width=result.width||width;height=result.height||height;
 const blank=!result.url||result.url==='about:blank';if(document.activeElement!==byId('url'))byId('url').value=blank?'':result.url;
 if(blank){empty('Henüz bir web sayfası açık değil','Dot’a bir site açmasını söyle veya yukarıya web adresi yaz.');}
 else if(result.screenshotId){const image=await fetch('./viewer/screenshots/'+encodeURIComponent(result.screenshotId)+'?t='+encodeURIComponent(cfg.token));if(!image.ok)throw new Error('Ekran görüntüsü alınamadı');const next=URL.createObjectURL(await image.blob());const previous=objectUrl;byId('screen').src=next;await byId('screen').decode().catch(error=>{URL.revokeObjectURL(next);throw error;});byId('screen').hidden=false;byId('empty').hidden=true;objectUrl=next;if(previous)URL.revokeObjectURL(previous);}
 byId('status').textContent=control==='user'?'Kontrol sende':blank?'Tarayıcı bağlı · Sayfa açılması bekleniyor':'Dot kontrolünde';
 }catch(error){byId('status').textContent=error.message;if(!ready)empty('Tarayıcı görüntüsü yüklenemedi',error.message);}finally{busy=false;controls();}};
byId('navigate').onsubmit=e=>{e.preventDefault();request('navigate',{url:byId('url').value});};byId('take').onclick=()=>request('takeover');byId('release').onclick=()=>request('release');byId('type').onclick=()=>request('type',{text:byId('text').value});byId('press').onclick=()=>request('press',{key:byId('key').value});byId('shot').onclick=()=>request(ready?'screenshot':'open');byId('screen').onclick=e=>{if(control!=='user'||!sessionId)return;const rect=e.target.getBoundingClientRect();request('click',{x:(e.clientX-rect.left)*width/rect.width,y:(e.clientY-rect.top)*height/rect.height});};request('open');setInterval(()=>{if(ready&&!busy&&!document.hidden)request('screenshot',{},true);},2000);
</script></body></html>`;
}
