import {randomUUID} from 'node:crypto';import type {RecordStore} from '@dots/contracts';
export interface SetupRequest {kind:'debian'|'custom';distribution:string;imagePath?:string;sha256?:string;}
export class ComputerSetup {
 constructor(private store:RecordStore){for(const j of store.list<any>('computer_setup').filter(j=>j.status==='running'))store.put('computer_setup',{...j,status:'failed',error:'Sunucu kurulum sırasında yeniden başlatıldı. Dağıtım korunur; durumu kontrol edip yeniden deneyin.',updatedAt:new Date().toISOString()});}
 status(){return this.store.list<any>('computer_setup').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);}
 queue(input:SetupRequest){if(!/^Damndots-[A-Za-z0-9-]{1,40}$/.test(input.distribution))throw Object.assign(Error('Dağıtım adı Damndots- ile başlamalı ve yalnız harf/rakam/tire içermeli.'),{statusCode:400});if(input.kind==='custom'&&(!input.imagePath||! /^[A-Za-z]:[\\/].+\.(tar|tar\.gz|tgz|wsl)$/i.test(input.imagePath)||input.imagePath.includes('\0')||! /^[a-f0-9]{64}$/i.test(input.sha256||'')))throw Object.assign(Error('Özel Linux için yerel .tar/.tar.gz/.wsl rootfs yolu ve SHA256 gerekli; ISO WSL imajı değildir.'),{statusCode:400});if(this.status().some(j=>['queued','running'].includes(j.status)))throw Object.assign(Error('Bir bilgisayar kurulumu zaten sürüyor.'),{statusCode:409});return this.store.put('computer_setup',{id:randomUUID(),...input,status:'queued',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),error:null});}
 next(){const job=this.status().find(j=>j.status==='queued');if(!job)return null;return this.store.put('computer_setup',{...job,status:'running',updatedAt:new Date().toISOString()});}
 finish(id:string,result:{status:'completed'|'failed';error:string|null}){const job=this.store.get<any>('computer_setup',id);if(!job||job.status!=='running')throw Error('No active setup job');return this.store.put('computer_setup',{...job,...result,updatedAt:new Date().toISOString()});}
}
