import type {FastifyInstance} from 'fastify';
import type {Schedule} from '@dots/contracts';
import type {NativeContext} from './native.js';
const stamp=(iso:string)=>Date.parse(iso)/1000;
export function nativeAutomation(ctx:NativeContext,s:Schedule){const dot=ctx.runtime.getDot(s.dotId);const extra=ctx.store.get<any>('native_automation_metadata',s.id)||{};let schedule=s.rrule||'';let frequency='custom';
  if(s.kind==='interval'){const seconds=s.intervalSeconds||1;schedule=`BEGIN:VEVENT\nRRULE:FREQ=SECONDLY;INTERVAL=${seconds}\nEND:VEVENT`;frequency=seconds%86400===0?'daily':seconds%3600===0?'hourly':'custom';}
  if(s.kind==='once'){schedule=`BEGIN:VEVENT\nDTSTART:${s.nextRunAt?new Date(s.nextRunAt).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'):''}\nEND:VEVENT`;frequency='once';}
  if(s.kind==='rrule'){const match=schedule.match(/FREQ=([A-Z]+)/);frequency=match?match[1].toLowerCase().replace('ly',''):'once';}
  return {id:s.id,title:s.title,display_title:s.title,display_emoji:extra.emoji||null,prompt:s.prompt,schedule,display_schedule:s.kind==='cron'?`cron: ${s.cron} (${s.timezone})`:null,schedule_components:{frequency,interval:s.intervalSeconds,start_time:s.nextRunAt},timing_mode:extra.timing_mode||'exact_schedule',next_run_times:s.enabled&&s.nextRunAt?[s.nextRunAt]:[],is_enabled:s.enabled,default_timezone:s.timezone,created_at:stamp(s.createdAt),updated_at:stamp(s.updatedAt),executor:'local',thread_mode:extra.thread_mode||'existing_chat',conversation_id:dot.rootThreadId,model:dot.model,reasoning_effort:dot.reasoningEffort,email_enabled:!!extra.email_enabled,notifications_enabled:extra.notifications_enabled!==false,current_user_role:'owner',can_delete:true,team_id:null};
}
export function registerNativeAutomations(app:FastifyInstance,ctx:NativeContext){
  app.get('/automations',async req=>{const q=req.query as any,limit=Math.min(100,Math.max(1,Number(q.limit)||25)),items=ctx.runtime.listSchedules().map(s=>nativeAutomation(ctx,s));return {items:items.slice(0,limit),automations:items.slice(0,limit),cursor:null,next_cursor:null};});
  app.get('/amphora/notifications',async()=>({notifications:[],items:[],cursor:null}));
  app.post('/amphora/clear_settings_cache',async()=>({}));
  app.get('/automation/:automationId',async req=>{const id=(req.params as any).automationId,s=ctx.runtime.listSchedules().find(s=>s.id===id);if(!s)throw Object.assign(new Error('Schedule not found'),{statusCode:404});return nativeAutomation(ctx,s);});
  app.post('/automation/:automationId/run',async req=>{const id=(req.params as any).automationId,key=(req.body as any)?.idempotency_key;if(key){const prior=ctx.store.get<any>('native_schedule_requests',`${id}:${key}`);if(prior)return ctx.runtime.getTask(prior.taskId);}const task=ctx.runtime.runSchedule(id);if(key)ctx.store.put('native_schedule_requests',{id:`${id}:${key}`,taskId:task.id});return {task_id:task.id,thread_id:task.threadId,status:task.status};});
  app.post('/automations/set_status',async req=>{const b=req.body as any;const s=ctx.runtime.updateSchedule(b.jawbone_id,{enabled:!!b.is_enabled});return nativeAutomation(ctx,s);});
  app.post('/automations/remove',async req=>{ctx.runtime.deleteSchedule((req.body as any).automation_id);return {};});
  app.post('/automations/save',async req=>{const b=req.body as any,old=b.jawbone_id?ctx.runtime.listSchedules().find(s=>s.id===b.jawbone_id):undefined;const dotId=old?.dotId||b.tbo_id||ctx.runtime.listDots().find(d=>d.rootThreadId===b.conversation_id)?.id||ctx.runtime.listDots().find(d=>d.rootThreadId)?.id;if(!dotId)throw Object.assign(new Error('Choose a dot first'),{statusCode:409});if(typeof b.schedule!=='string'||!b.schedule.trim())throw Object.assign(new Error('A valid VEVENT/RRULE schedule is required'),{statusCode:400});
    const value={title:b.title,prompt:b.prompt,kind:'rrule' as const,rrule:b.schedule,timezone:b.default_timezone||old?.timezone||'UTC',enabled:b.is_enabled!==false};const s=old?ctx.runtime.updateSchedule(old.id,value):ctx.runtime.createSchedule({...value,dotId});ctx.store.put('native_automation_metadata',{id:s.id,timing_mode:b.timing_mode===1?'flexible_schedule':b.timing_mode===2?'condition_watch':'exact_schedule',thread_mode:b.thread_mode||'existing_chat',emoji:b.emoji,email_enabled:!!b.email_enabled,notifications_enabled:b.notifications_enabled!==false});return nativeAutomation(ctx,s);});
}
